# Sets some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# create empty scene
#
/vis/scene/create

# Use this open statement instead for OpenGL in immediate mode.
/vis/open OGL 600x600-0+0


# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector  1 1 1
/vis/viewer/set/lightsVector -1 0 0

# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

#
# Draw trajectories at end of event, showing trajectory points as
# markers of size 2 pixels
/vis/scene/add/trajectories
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# To draw gammas only
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To draw charged particles only
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# To draw positive charge particl only
#/vis/filtering/trajectories/create/chargeFilter
#/vis/filtering/trajectories/chargeFilter-0/add +1



#
# Many other options available with /vis/modeling and /vis/filtering.
# For example, select colour by particle ID
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- 1  0.6  0.0  1
/vis/modeling/trajectories/drawByParticleID-1/setRGBA e- 1  0.6  0.0  1
/vis/modeling/trajectories/drawByParticleID-0/set mu+ grey 
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set nu_e yellow 
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_mu blue 
#
/vis/scene/endOfEventAction accumulate
#


# Make the "World" box visible
#/vis/geometry/set/visibility World 0 false
/vis/geometry/set/colour World 0 0 1 0 .1
/vis/viewer/set/style surface
#/vis/viewer/set/hiddenMarker true

# "Envelope" is transparent blue to represent water
/vis/geometry/set/colour Envelope 0 0 0 1 .3
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 110 90

/vis/geometry/set/colour Shape1 0 0 1 0 1
