# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0


# if tracking verbose is more than 0, it can cause the "memory-leak-like" problem
#/tracking/verbose 1
# 

#/gun/particle e-
#/gun/energy 1000 keV


#
/run/beamOn 800
